import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Logo from "./logo"
import "./globals.css";
import {topics} from "@/app/SelectiveTopic";
import React from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juho's Portfolio Site",
  description: "Generated by Juho",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="ko"><body className={inter.className}>
      <Logo></Logo>
      <div className="flex flex-row box-border border-4 justify-evenly">
        <Topic topic = {topics.GameDevelopment}></Topic>
        <Topic topic = {topics.WebDevelopment}></Topic>
        <Topic topic = {topics.ApplicationDevelopment}></Topic>
      </div>




      {children}

    </body></html>
  );
}
interface TopicProps {
  topic : string;
}

function Topic({ topic } : TopicProps){
  switch (topic){
    case topics.ApplicationDevelopment:
    case topics.GameDevelopment:
    case topics.WebDevelopment:{
      return(
          <li><div><a href={"/"+topic}><img className="size-52 transition duration-150 ease-out hover:scale-125" src={"/"+topic+".png"} alt={topic}/></a></div></li>
      );
    }
    default:{
      return <></>
    }
  }

}